# grafana

grafana:
  enabled: true
  # admon password will be base64 decoded, security reasons it will not be published here
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: issuer
    hosts:
    - grafana.tahirbajramselita.co.uk
    tls:
      - secretName: grafana-tls
        hosts:
        - grafana.tahirbajramselita.co.uk

# prometheus

prometheus:
  enabled: true

  ingress:  
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: issuer
    hosts:
    - "prometheus.tahirbajramselita.co.uk"
    tls:
      - secretName: prometheus-tls
        hosts:
        - "prometheus.tahirbajramselita.co.uk"
