name: terraform apply, update kubectl config, certman and argocd

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-west-2
  EKS_CLUSTER_NAME: eks-project

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply-k8s-config:
    name: terraform apply, update kubectl config, certman and argocd
    runs-on: ubuntu-latest
    
    steps:
    - name: check out code
      uses: actions/checkout@v4
        
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_OIDC }}

# terraform steps:

    - name: hashicorp - terraform setup
      uses: hashicorp/setup-terraform@v3

    - name: terraform init
      working-directory: ./deployment/terraform
      run: terraform init

    - name: terraform apply
      working-directory: ./deployment/terraform
      run: terraform apply -auto-approve

# kubernetes steps:

    - name: configure kubectl config
      run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

    - name: Apply certificate manager
      run: kubectl apply -f deployment/cert-man/issuer.yaml

    - name: Deploy ArgoCD Application
      run: kubectl apply -f /deployment/argo-cd/apps-argocd.yaml